### ISSUE TITLE
Unable to set null to false on model

### ISSUE THREAD

**Issue by atbyrd** [neo4jrb/devise-neo4j#29]
I have a devise model, Candidates. When I set the null option to false. I'm unable to run the server or any migrations.

### Model

`  property :email, type: String, null: false, default: ''
`
#### Error

>  gems/neo4j-8.0.1/lib/neo4j/shared/property.rb:150:in `property': Invalid options for property `email` on `Candidate`: null (ArgumentError)

**Comment by cheerfulstoic** [comment]
Hello again! ;)

Try the `Gemfile` change that I suggest here: https://github.com/neo4jrb/neo4j/issues/1334

The reason that this is happening is because the `devise-neo4j` model generator has always had `null: false` in there, but it has never actually been a supported option.  In 8.0 we start giving errors if you give invalid options so that people know when something isn't right.  The model generator in that new branch removes the `null` option (among other things)

**Comment by atbyrd** [comment]
@cheerfulstoic This seems to fix this error but not the other issue. 

Thanks

**Comment by atbyrd** [comment]
@cheerfulstoic I was mistaken. This issue isn't resolved either. I forgot to update my model with the null attribute.

**Comment by cheerfulstoic** [comment]
I'm not sure what you mean... Do you mean the `null` option on the properties?  There is no `null` option supported so you need to leave that out for things to work.  The problem was that the `devise-neo4j` generator was putting it in but it shouldn't be there

**Comment by cheerfulstoic** [comment]
Also to clarify, to keep the property from being `null` you should use a validation.  That's why the generator now has `validates :email, presence: true` below the property definition

**Comment by atbyrd** [comment]
@cheerfulstoic Thanks for the clarification.

**Comment by cheerfulstoic** [comment]
Awesome.  I just released version 2.1.0 of `devise-neo4j` with this new model generator.  The tests are still failing, but I think it's due to compatibility between changes in the `devise` gem and the various tricks that were made to get this gem to work against the `devise` tests.  I've been using this gem against 8.0.0 of `neo4j` for a while now without issues.
